"""init migrations

Revision ID: 789953bf9c87
Revises: 
Create Date: 2025-03-10 06:29:23.895719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789953bf9c87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('found_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_items_id'), 'found_items', ['id'], unique=False)
    op.create_index(op.f('ix_found_items_name'), 'found_items', ['name'], unique=False)
    op.create_table('lost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lost_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_items_id'), 'lost_items', ['id'], unique=False)
    op.create_index(op.f('ix_lost_items_name'), 'lost_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_items_name'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_id'), table_name='lost_items')
    op.drop_table('lost_items')
    op.drop_index(op.f('ix_found_items_name'), table_name='found_items')
    op.drop_index(op.f('ix_found_items_id'), table_name='found_items')
    op.drop_table('found_items')
    # ### end Alembic commands ###
