"""all categories

Revision ID: 997f18b6be3d
Revises: 789953bf9c87
Create Date: 2025-09-19 11:47:37.135158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997f18b6be3d'
down_revision: Union[str, None] = '789953bf9c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.alter_column('found_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('lost_items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('lost_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'lost_items', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lost_items', type_='foreignkey')
    op.alter_column('lost_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('lost_items', 'category_id')
    op.alter_column('found_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
